use master
go

if exists (select name from sysdatabases where name = 'DB_ChinhChinh')
	drop database DB_ChinhChinh
go

create database DB_ChinhChinh
go

use DB_ChinhChinh
go

CREATE TABLE [ROLE]
(
	MAROLE INT IDENTITY(1 ,1) PRIMARY KEY,
	TENROLE NVARCHAR(20),
	CHIETKHAU REAL
)

CREATE TABLE CUSTOMER 
(
	EMAILCUS VARCHAR(100) PRIMARY KEY,
	MATKHAU VARCHAR(MAX),
	CUSNAME NVARCHAR(MAX),
	[ADDRESS] NVARCHAR(MAX),
	PHONE VARCHAR(11),
	MAROLE INT,
	CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY (MAROLE) REFERENCES [ROLE](MAROLE)
)

CREATE TABLE CATEGORY
(
	IDCATE INT IDENTITY(1, 1) PRIMARY KEY,
	TENCATE NVARCHAR(50)
)

CREATE TABLE PRODUCT
(
	IDPRO INT IDENTITY(1 ,1) PRIMARY KEY,
	IDCATE INT,
	NAMEPRO NVARCHAR(100),
	DESCRIPTIONPRO NVARCHAR(MAX),
	PRICE MONEY,
	IMAGEPRO VARCHAR(MAX),
	QUANTITY TINYINT, 
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (IDCATE) REFERENCES CATEGORY(IDCATE)
)

CREATE TABLE CART
(
	IDCART INT IDENTITY(1, 1) PRIMARY KEY,
	EMAILCUS VARCHAR(100),
	IDPRO INT,
	QUANTITY TINYINT,
	CONSTRAINT FK_CART_CUSTOMER FOREIGN KEY (EMAILCUS) REFERENCES CUSTOMER(EMAILCUS),
	CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (IDPRO) REFERENCES PRODUCT(IDPRO)
)

CREATE TABLE [ORDER] 
(
	IDORDER INT IDENTITY(1, 1) PRIMARY KEY,
	EMAILCUS VARCHAR(100) NULL,
	[ADDRESS] NVARCHAR(MAX),
	DATEORDER DATE,
	DATEACCEPT DATE,
	DATESHIPPING DATE,
	DATERECEIVE DATE,
)

CREATE TABLE ORDERDETAIL
(
	IDORDERDETAIL INT IDENTITY(1, 1) PRIMARY KEY,
	
	IDORDER INT,
	IDPRO INT,
	QUANTITY SMALLINT,
	[STATUS] NVARCHAR(30),
	CONSTRAINT FK_ORDERDETAIL_ORDER FOREIGN KEY (IDORDER) REFERENCES [ORDER] (IDORDER),
	CONSTRAINT FK_ORDERDETAIL_PRODUCT FOREIGN KEY (IDPRO) REFERENCES PRODUCT(IDPRO),
)

CREATE TABLE BILL
(
	IDBILL INT IDENTITY(1, 1) PRIMARY KEY,
	DATEBILL DATE,
	EMAILCUS VARCHAR(100) NULL,
	[ADDRESS] NVARCHAR(MAX)
)

CREATE TABLE BILLDETAIL
(
	IDBILLDETAIL INT IDENTITY(1, 1) PRIMARY KEY,
	IDBILL INT,
	IDPRO INT,
	QUANTITY SMALLINT,
	CONSTRAINT FK_BILLDETAIL_BILL FOREIGN KEY (IDBILL) REFERENCES BILL(IDBILL),
	CONSTRAINT FK_BILLDETAIL_PRODUCT FOREIGN KEY (IDPRO) REFERENCES PRODUCT(IDPRO),
)

CREATE TABLE COMMENT
(
	IDCMT INT IDENTITY(1, 1) PRIMARY KEY,
	EMAILCUS VARCHAR(100),
	GRADES TINYINT,
	CONTENT VARCHAR(MAX),
	DATECMT DATE,
	CONSTRAINT FK_COMMENT_CUSTOMER FOREIGN KEY (EMAILCUS) REFERENCES CUSTOMER(EMAILCUS)
)

CREATE TABLE VERIFYCODE(
	IDVERIFY INT IDENTITY(1, 1) PRIMARY KEY,
	EMAILCUS VARCHAR(100),
	CODE INT
)

INSERT INTO [ROLE] (TENROLE, CHIETKHAU) VALUES ('ADMIN', 0)
INSERT INTO [ROLE] (TENROLE, CHIETKHAU) VALUES ('CUSTOMER', 0)
INSERT INTO [ROLE] (TENROLE, CHIETKHAU) VALUES ('CUSTOMER_VIP', 10.0/100)

INSERT INTO CUSTOMER VALUES ('chinhchinh@gmail.com', '123456', 'Chinh Chinh', NULL, null , '1')
INSERT INTO CUSTOMER VALUES ('chinhchinhdemo@gmail.com', '123456', 'KH1', N'111, Mỹ Hòa, Trung Chánh, Hóc Môn', null, '2')

INSERT INTO CATEGORY (TENCATE) VALUES (N'ÁO KHOÁC')
INSERT INTO CATEGORY (TENCATE) VALUES (N'TÚI XÁCH DA')
INSERT INTO CATEGORY (TENCATE) VALUES (N'GIÀY DA')
INSERT INTO CATEGORY (TENCATE) VALUES (N'ÁO SƠ MI')
INSERT INTO CATEGORY (TENCATE) VALUES (N'VESTON')
INSERT INTO CATEGORY (TENCATE) VALUES (N'QUẦN ỐNG DÀI')
INSERT INTO CATEGORY (TENCATE) VALUES (N'QUẦN ỐNG NGẮN')
INSERT INTO CATEGORY (TENCATE) VALUES (N'ÁO THUN')
INSERT INTO CATEGORY (TENCATE) VALUES (N'BALO')


INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (3, N'GIẦY DA', N'SANG TRỌNG', 1500000, 'product-3.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (4, N'ÁO SƠ MI', N'QUÝ PHÁI', 500000, 'product-12.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (4, N'ÁO SƠ MI ĐEN', N'QUÝ PHÁI', 500000, 'product-13.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (4, N'ÁO SƠ MI VỆT SƠN',  N'LỊCH LÃM', 600000, 'product-14.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (3, N'GIÀY DA 3', N'QUÝ PHÁI', 2000000, 'product-15.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (6, N'QUẦN KAKI', N'QUÝ PHÁI', 500000, 'product-16.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (7, N'QUẦN SHORT JEANS', N'QUÝ PHÁI', 500000, 'product-17.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (7, N'QUẦN JOGGER', N'QUÝ PHÁI', 500000, 'product-18.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (8, N'ÁO THUN BASIC', N'CHẤT VẢI DÀY', 500000, 'product-5.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (1, N'ÁO KHOÁC CHANEL', N'Mặc thoáng', 500000, 'product-2.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (9, N'BALO BASIC', N'Màu cũng đẹp', 500000, 'product-9.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (9, N'BALO GUCCI', N'Da 100%', 600000, 'product-6.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (8, N'ÁO THUN DÂN CHƠI', N'hehe', 200000, 'product-8.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (8, N'ÁO THUN CỔ KIỂU', N'Áo thun cổ kiểu', 200000, 'product-7.jpg', 5)
INSERT INTO PRODUCT (IDCATE, NAMEPRO, DESCRIPTIONPRO, PRICE, IMAGEPRO, QUANTITY) 
VALUES (1, N'ÁO KHOÁC HỌA TIẾT CAMO', N'Cá tính', 500000, 'product-10.jpg', 5)



SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'



--CẬP NHẬT SỐ LƯỢNG SẢN PHẨM CÓ MÃ LÀ 1 LÊN 10 SẢN PHẨM
UPDATE PRODUCT
SET QUANTITY = 10
WHERE IDPRO = 1

SELECT* FROM CATEGORY
SELECT* FROM CUSTOMER
SELECT* from [ROLE]
SELECT* FROM PRODUCT
SELECT* FROM [ORDER]
SELECT* FROM ORDERDETAIL
SELECT* FROM BILL
SELECT* FROM BILLDETAIL
SELECT* FROM COMMENT
SELECT* FROM CART
SELECT* FROM VERIFYCODE

DELETE CUSTOMER
WHERE EMAILCUS = 'chinhchi123nh@gmail.com'