//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChingChing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int IDCMT { get; set; }
        public string EMAILCUS { get; set; }
        public Nullable<byte> GRADES { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> DATECMT { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
