//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChingChing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public int IDORDERDETAIL { get; set; }
        public string EMAILCUS { get; set; }
        public Nullable<int> IDORDER { get; set; }
        public Nullable<int> IDPRO { get; set; }
        public Nullable<short> QUANTITY { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
