//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChingChing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
        }
    
        public int IDORDER { get; set; }
        public Nullable<System.DateTime> DATEORDER { get; set; }
        public Nullable<System.DateTime> DATEACCEPT { get; set; }
        public Nullable<System.DateTime> DATESHIPPING { get; set; }
        public Nullable<System.DateTime> DATERECEIVE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAILCUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
    }
}
