//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChingChing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERIFYCODE
    {
        public int IDVERIFY { get; set; }
        public string EMAILCUS { get; set; }
        public Nullable<int> CODE { get; set; }
    }
}
